# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/verker_bee.rb'

Hoe.new('verker_bee', VerkerBee::VERSION) do |p|
  # p.rubyforge_name = 'verker_beex' # if different than lowercase project name
  p.developer('John Howe', 'johnhowe@arashi.com')
end

# vim: syntax=Ruby
